base:
  path:
    project: "{{cookiecutter.project_name}}" # change it
    python: "~/miniconda3/envs/{{cookiecutter.project_slug}}/bin/python" # change it
    logs: "logs/"
    log_config: "configs/logging.yaml"


dev:
  bigq:
    destination:

  presto:
    host:
    port:
    username:

  kafka:
    bootstrap_servers:
    topic:

prod:
  bigq:
    destination:

  presto_prod:
    host:
    port:
    username:

  kafka:
    bootstrap_servers:
    topic:
